INSERT INTO category (name)
VALUES ('Concerts')
     , ('Festivals')
     , ('Conferences')
     , ('Workshops')
     , ('Seminars')
     , ('Arts and Culture')
     , ('Food and Drink')
     , ('Charity and Fundraising')
     , ('Health and Wellness')
     , ('Technology')
     , ('Business and Entrepreneurship')
     , ('Education')
     , ('Family and Kids')
     , ('Outdoor and Adventure')
     , ('Comedy')
     , ('Film and Cinema')
     , ('Music')
     , ('Performing Arts')
     , ('Classic Literature')
     , ('Comedy')
     , ('Drinks')
     , ('Fitness and Workouts')
     , ('Foods')
     , ('Games')
     , ('Gardening')
     , ('Healthy Living and Self Care')
     , ('Home and Garden')
     , ('Parties')
     , ('Religions')
     , ('Shopping')
     , ('Social Issues')
     , ('Sports')
     , ('Theater');

INSERT INTO keyword (name)
VALUES ('Live Music')
     , ('Dance')
     , ('Art Exhibition')
     , ('Science')
     , ('Coding')
     , ('Gaming')
     , ('Yoga')
     , ('Meditation')
     , ('Fitness')
     , ('Food Tasting')
     , ('Networking')
     , ('Fashion Show')
     , ('Photography')
     , ('Charity Auction')
     , ('Marathon')
     , ('Theater')
     , ('Poetry')
     , ('Wine Tasting')
     , ('TEDx')
     , ('Hackathon')
     , ('Rock')
     , ('Jazz')
     , ('Hip-Hop')
     , ('Electronic Music')
     , ('Classical Performance')
     , ('Country Music')
     , ('Indie')
     , ('Acoustic Jam Session')
     , ('Blues')
     , ('Reggae Night')
     , ('Beer')
     , ('Wine Tasting')
     , ('Cocktail')
     , ('Coffee Tasting')
     , ('Whiskey Tasting')
     , ('BBQ')
     , ('Vegan')
     , ('International Cuisine')
     , ('Football')
     , ('Basketball')
     , ('Marathon')
     , ('Yoga')
     , ('Cycling')
     , ('Golf')
     , ('Tennis')
     , ('Surfing')
     , ('Street Art')
     , ('Photography Exhibition')
     , ('Fashion Show')
     , ('Poetry Slam')
     , ('Cultural Heritage')
     , ('Dance Performance')
     , ('Theater Play')
     , ('Sculpture Expo');