INSERT INTO achievement(id, name, description, reward, icon)
VALUES (0, 'Un Assigned', 'Default value', 0, ''),
       (1, 'Canary 1', 'Join in 5 music related events', 100, ''),
       (2, 'Canary 2', 'Join in 20 music related events', 200, ''),
       (3, 'Canary 3', 'Join in 50 music related events', 270, ''),
       (4, 'Owl 1', 'Join in 5 educational or learning related events', 100, ''),
       (5, 'Owl 2', 'Join in 20 educational or learning related events', 200, ''),
       (6, 'Owl 3', 'Join in 50 educational or learning related related events', 270, ''),
       (7, 'Peacock 1', 'Join in 5 cultural or artistic related events', 100, ''),
       (8, 'Peacock 2', 'Join in 20 cultural or artistic related events', 200, ''),
       (9, 'Peacock 3', 'Join in 50 cultural or artistic related related events', 270, ''),
       (10, 'Bear 1', 'Join in 5 food or drink related events', 100, ''),
       (11, 'Bear 2', 'Join in 20 food or drink related events', 200, ''),
       (12, 'Bear 3', 'Join in 50 food or drink related related events', 270, ''),
       (13, 'Butterfly 1', 'Join in 5 social or community based related events', 100, ''),
       (14, 'Butterfly 2', 'Join in 20 social or community related events', 200, ''),
       (15, 'Butterfly 3', 'Join in 50 social or community related related events', 270, ''),
       (16, 'Cheetah 1', 'Join in 5 sport or physically active events', 100, ''),
       (17, 'Cheetah 2', 'Join in 20 sport or physically active events', 200, ''),
       (18, 'Cheetah 3', 'Join in 50 sport or physically active related events', 270, ''),
       (19, 'Monkey 1', 'Join in 5 recreational or hobby based events', 100, ''),
       (20, 'Monkey 2', 'Join in 20 recreational or hobby based events', 200, ''),
       (21, 'Monkey 3', 'Join in 50 recreational or hobby based related events', 270, ''),
       (22, 'New comer', 'Fill out the interest survey', 0, '');
      